### ISSUE TITLE
React-hook-form bundling issue ?

### ISSUE THREAD

**Issue by revskill10** [unstubbable/mfng#15]
I've tried use `react-hook-form` with client component, but always get webpack error: `Uncaught TypeError: Cannot read property 'call' of undefined` .

Could you provide example of using external library ? I guess it's webpack bundling issue somehow.

**Comment by lubieowoce** [comment]
I'm not a maintainer or anything, but this is pretty hard to debug without a repro case on stackblitz/codesandbox. if you could make one I might be able to take a look
