### ISSUE TITLE
Server action: Example of bound arguments server action.

### ISSUE THREAD

**Issue by revskill10** [unstubbable/mfng#22]
Could we write and use server action like this ?

```js
'use server'

const action = (boundArgs) => async (args) => {
   //...
}
```
From server component, we want to pass in `boundArgs`
```js

function ServerComponent(): {
const boundargs = `blahblah`;
return <Component action={action(boundargs)} />
}
```

**Comment by lubieowoce** [comment]
AFAIK, code like what you wrote (and all actions that _aren't top-level functions_ in general) would require inline `"use server"`. I'm not sure if MFNG supports that.
```
const action = (boundArgs) => async (args) => {
  "use server"
   //...
}
```

You should, however, be able to pass those args in using `.bind()`, which has some special support in RSC and should Just Work(TM):

```
'use server'
export const action = async (boundArgs, args) => { ... }
```

```
function ServerComponent(): {
  const boundargs = `blahblah`;
  return <Component action={action.bind(null, boundargs)} />
}
```

**Comment by revskill10** [comment]
@lubieowoce My intention is, how to "implicitly" bind `boundArgs` on the server side.

**Comment by unstubbable** [comment]
Thanks for jumping in here, @lubieowoce!

- ✅ The explicit bind currently works inside of a client component in MFNG.
- ⌛ I'm thinking about adding support for explicit binding in server components as well.
- ❌ The variant you requested, @revskill10, I can/will not support.
- ❌ And as mentioned [on Twitter](https://x.com/unstubbable/status/1719414530176897392?s=20) I probably won't add support for non-module `'use server'` directives.
