### ISSUE TITLE
Potentially mistaken dependency `react-react`

### ISSUE THREAD

**Issue by jeduan** [unstubbable/mfng#66]
Hi! 

I'm learning how to use react server components and this repo has been a great help.

I noticed that `mfng/core` includes a `peerDependency` to `react-react`. I wasn't familiar with [the package](https://npm.io/package/react-react) but it's a "state management toolkit for react" that supports only up to react 16.

https://github.com/unstubbable/mfng/blob/1fe9772d6bb1e49322012f9f94d8375334a6358e/packages/core/package.json#L58

I found this because installing the package had a warning

```bash
❯ pnpm add @mfng/core
Packages: +4
++++
Progress: resolved 121, reused 121, downloaded 0, added 0, done

dependencies:
+ @mfng/core 4.1.2

 WARN  Issues with peer dependencies found
 WARN  Issues with peer dependencies found
.
└─┬ react-react 1.2.0
  └── ✕ unmet peer react@"^14.0.0 || ^15.0.0 || ^16.0.0": found 18.3.0-canary-c3048aab4-20240326
```

Was it the intention to add a `peerDependency` on this package?

**Comment by unstubbable** [comment]
Thanks for the report! This was indeed unintentional.

**Comment by jeduan** [comment]
@unstubbable Wow, thank you for the quick fix!
